

INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (37,'Vulpix','Fire','Rocket');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (6,'Charizard','Fire','Hash');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (126,'Magmar','Fire','Hash');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (154,'Cyndaquil','Fire','Brok');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (653,'Fennekin','Fire','Brok');


INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (134,'Vaporeon','Water','Brok');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (55,'Golduck','Water','Victoria');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (99,'Kingler','Water','Victoria');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (129,'Magikarp','Water','Rocket');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (131,'Lapras','Water',null);


INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (1,'Bulbasaur','Grass',null);
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (71,'Victreebel','Grass','Hash');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (152,'Chikorita','Grass','Rocket');
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (192,'Sunflora','Grass',null);
INSERT INTO POKEMON (ID,NAME,TYPE,TRAINER_NAME) VALUES (319,'Sharpedo','Grass',null);

INSERT INTO TRAINER (NAME,LEVEL,POKEMONS_BAG) VALUES ('Hash',2,'[6,126,71]');
INSERT INTO TRAINER (NAME,LEVEL,POKEMONS_BAG) VALUES ('Brok',0,'[154,653,134]');
INSERT INTO TRAINER (NAME,LEVEL,POKEMONS_BAG) VALUES ('Victoria',0,'[55,99]');
INSERT INTO TRAINER (NAME,LEVEL,POKEMONS_BAG) VALUES ('Misti',1,'[]');
INSERT INTO TRAINER (NAME,LEVEL,POKEMONS_BAG) VALUES ('Rocket',1,'[37,129,152]');